---
Name: siteroutes
After:
  - "#rootroutes"
  - "#coreroutes"
---
SilverStripe\Control\Director:
  rules:
    "api//$Method": "Toast\\Controllers\\ApiController"
    "_styleguide": "Toast\\Controllers\\StyleGuideController"
